baseURL = "https://mercnet.jaredisgray.com/"
languageCode = "en-us"
title = "MercNet"
theme = "harbor"
publishDir = "docs"
sectionPagesMenu = "main"
layoutDir = "layouts"

[params]
  mainSections = ["news", "jobs"]

[[params.nav]]
  identifier = "jobs"
  name = "Jobs"
  url = "/jobs/"
  weight = 3

[[params.nav]]
  identifier = "news"
  name = "News"
  url = "/news/"
  weight = 3
